# Generated by Django 5.1.6 on 2025-05-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testanalytics',
            name='test',
        ),
        migrations.DeleteModel(
            name='StudentProgress',
        ),
        migrations.DeleteModel(
            name='TestAnalytics',
        ),
    ]
