# Generated by Django 5.1.6 on 2025-05-03 17:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_remove_testanalytics_test_delete_studentprogress_and_more'),
        ('content', '0006_question_source'),
        ('examination', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('feedback', models.TextField(blank=True, default='')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('strength_topics', models.ManyToManyField(related_name='strengths', to='content.topic')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.subject')),
                ('weakness_topics', models.ManyToManyField(related_name='weaknesses', to='content.topic')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'subject'], name='analytics_s_student_6e10ee_idx')],
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='TestAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('average_score', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('difficulty_distribution', models.JSONField(default=dict)),
                ('question_analysis', models.JSONField(default=dict)),
                ('anomalies', models.JSONField(default=dict)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='examination.test')),
            ],
            options={
                'indexes': [models.Index(fields=['test'], name='analytics_t_test_id_020f78_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestAttemptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('completed_at', models.DateTimeField()),
                ('duration', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.test')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'completed_at'], name='analytics_t_student_e096ef_idx'), models.Index(fields=['test', 'completed_at'], name='analytics_t_test_id_26284f_idx')],
            },
        ),
    ]
