# Generated by Django 5.1.6 on 2025-05-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_alter_testattempt_student_alter_testattempt_test'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testattempt',
            unique_together=set(),
        ),
    ]
