# Generated by Django 5.1.6 on 2025-06-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0003_alter_testattempt_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresponse',
            name='selected_answer',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
