# Generated by Django 5.1.6 on 2025-06-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0004_alter_studentresponse_selected_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
