# Generated by Django 5.1.6 on 2025-06-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0005_testattempt_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testattempt',
            name='is_completed',
        ),
    ]
