# Generated by Django 5.1.6 on 2025-04-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_questionapproval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionApproval',
        ),
    ]
