# Generated by Django 5.1.6 on 2025-04-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_questionapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionapproval',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
    ]
