# Generated by Django 5.1.6 on 2025-05-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_questionapproval_review_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(default='manual', max_length=50),
        ),
    ]
