# Generated by Django 5.1.6 on 2025-04-16 19:16

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='E.164 formatted international number', max_length=20, null=True, unique=True, validators=[apps.accounts.validators.validate_phone_number], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='E.164 formatted international number', max_length=20, null=True, unique=True, validators=[apps.accounts.validators.validate_phone_number], verbose_name='phone number'),
        ),
    ]
