# Generated by Django 5.1.6 on 2025-05-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_approvalrequest'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='approvalrequest',
            name='unique_pending_request',
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.UniqueConstraint(fields=('user', 'status'), name='unique_pending_request'),
        ),
    ]
