# Generated by Django 5.1.6 on 2025-05-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_approvalrequest_unique_pending_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='qualifications',
            field=models.TextField(default='bscs', help_text='Professional certifications and degrees'),
            preserve_default=False,
        ),
    ]
